version: "3.8"
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - app-network

  ml_service:
    build: ./ml_service
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge